version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/app/src
      - .env:/user/app/.env
      - ./package.json:/usr/app/package.json
      #- ./node_modules:/usr/app/node_modules
    networks:
      - private
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'toor'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - "3406:3306" 
    volumes:
      - .db:/var/lib/mysql:rw
      #- ".db:/var/lib/mysql"
    user: mysql
    networks:
      - private
networks:
  private:
    driver: bridge
